Repository C-Vollono/PSD, pull requests merged in 2025-05, with the labels that each got.

#10 Modifica Readme
  README.md
Labels: documentation

#12 Inizio ADT Veicolo
  Orari.txt
  README.md
  Veicoli.txt
  Veicolo.c
  Veicolo.h
Labels: documentation

#14 Modifica file README per la leggibilità
  Hello_World.c
  README.md
  Veicolo.c
  Veicolo.h
Labels: documentation

#16 Modifica indici veicolo.c
  Veicolo.c
  Veicolo.h
Labels: documentation

#17 Aggiornamento veicolo.c
  .idea/.gitignore
  .idea/PSD.iml
  .idea/editor.xml
  .idea/modules.xml
  .idea/vcs.xml
  Veicolo.c
  Veicolo.h
Labels: documentation

#18 Modifica indici veicolo.c
  .idea/.gitignore
  .idea/PSD.iml
  .idea/editor.xml
  .idea/modules.xml
  .idea/vcs.xml
  Veicolo.c
  Veicolo.h
Labels: documentation

#20 Aggiunta della sezione menu, ancora da implementare correttamente (bozza)
  Menu.c
  Menu.h
Labels: enhancement

#22 Aggiornamento con commenti Veicolo.c e rimozione funzione in Veicolo.h
  README.md
  Veicolo.c
  Veicolo.h
Labels: documentation

#23 Terminazione commenti del file Veicolo.c
  Veicolo.c
Labels: documentation

#28 Aggiunta local time e gestione storico
  Menu.c
  Prenotazione.c
  Prenotazione.h
  StoricoPrenotazioni
Labels: documentation

#29 Modifica del Menu.c
  .idea/workspace.xml
  Menu.c
  Menu.h
Labels: enhancement

#31 Ordinamento del codice
  .idea/workspace.xml
  Menu.c
  main.c
Labels: documentation

#32 Inizio testing
  Makefile
  Menu.c
  Menu.h
  Menu.o
  Prenotazione.c
  Prenotazione.h
  Prenotazione.o
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
  utente.txt
Labels: documentation

#34 Continuo testing
  Menu.c
  Orari.txt
  Prenotazione.c
  Prenotazione.o
  Veicolo.c
  Veicolo.o
  main.c
  main.exe
  main.o
  utente.txt
Labels: documentation

#38 Risoluzione di problematiche varie, controllo funzionalità
  .vscode/settings.json
  Menu.c
  Menu.h
  Menu.o
  PSD.code-workspace
  Prenotazione.c
  Prenotazione.o
  Veicolo.c
  Veicolo.o
  main.c
  main.exe
  main.o
  utente.txt
Labels: documentation

#40 Commenti aggiunti
  Veicolo.c
  Veicolo.h
Labels: documentation

#41 Adattamento funzione stampa
  .vscode/settings.json
  Menu.c
  Menu.o
  Prenotazione.c
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.o
  main.c
  main.exe
  main.o
Labels: documentation

#42 Correzione bug vari
  Menu.c
  PSD.code-workspace
  Prenotazione.c
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.h
  main.c
  main.exe
Labels: documentation

#44 Aggiustamenti per un'implementazione corretta della tabella Hash
  Prenotazione.c
  Prenotazione.h
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicoli.txt
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
Labels: documentation

#46 Stampa sistemata trovaprenotazione, Trovati bug
  StoricoPrenotazioni.txt
  main.c
  main.exe
  main.o
  utente.txt
Labels: bug, documentation

#47 Rifiniture funzionalità codice e inizio Testing
  .vscode/tasks.json
  Menu.c
  Menu.h
  Prenotazione.c
  Prenotazione.h
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
Labels: documentation

#48 Completamento e ultimi ritocchi codice
  Menu.o
  Prenotazione.c
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
Labels: documentation

#50 Modifiche relative al modo di elaborare l'input utente
  Menu.c
  Menu.h
  Menu.o
  Prenotazione.c
  Prenotazione.h
  Prenotazione.o
  README.md
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
Labels: documentation

#51 Correzione inserimento input, correzione calcolo del costo noleggio
  Menu.c
  Menu.h
  Menu.o
  Prenotazione.c
  Prenotazione.o
  StoricoPrenotazioni.txt
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
  utente.txt
Labels: documentation

#52 Versione 1.5 carsharing
  Makefile
  Menu.o
  Prenotazione.c
  Prenotazione.h
  Prenotazione.o
  StoricoPrenotazioni.txt
  TabellaHash.c
  TabellaHash.h
  Utile.c
  Utile.h
  Veicolo.c
  Veicolo.h
  Veicolo.o
  main.c
  main.exe
  main.o
  utente.txt
Labels: enhancement

#53 Terminazione Specifiche TabellaHash.c
  Prenotazione.c
  Prenotazione.h
  TabellaHash.c
  Utile.c
  Veicolo.c
  Veicolo.h
  main.c
  utente.txt
Labels: documentation

#54 Terminati commenti sui file Veicolo
  Veicolo.c
  Veicolo.h
Labels: documentation

#58 Correzione finale commenti e specifiche
  Menu.c
  Menu.h
  Prenotazione.h
  StoricoPrenotazioni.txt
  TESTING/Menu.c
  TESTING/Menu.h
  TESTING/Menu.o
  TESTING/Prenotazione.c
  TESTING/Prenotazione.h
  TESTING/Prenotazione.o
  TESTING/TabellaHash.c
  TESTING/TabellaHash.h
  TESTING/TabellaHash.o
  TESTING/Testing.c
  TESTING/Testing.h
  TESTING/Testing.o
  TESTING/Utile.h
  TESTING/Utile.o
  TESTING/Veicolo.h
  TESTING/Veicolo.o
  TESTING/main.o
  TESTING/result.txt
  TESTING/testing.exe
  TabellaHash.c
  TabellaHash.h
  Utile.c
  Utile.h
  Veicolo.c
  Veicolo.h
  main.c
  utente.txt
Labels: documentation

#61 Correzione report
  Report Progetto PSD.pdf
Labels: documentation

#64 Bug nel testing
  TESTING/main.c
Labels: bug, documentation
